repos:
- hooks:
  - args:
    - --line-length
    - '88'
    id: black
  repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.0
- hooks:
  - additional_dependencies:
    - mypy
    args:
    - --python-version
    - '3.11'
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy/
  rev: v1.6.1
- hooks:
  - args:
    - --profile
    - black
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.12.0
- hooks:
  - args:
    - --max-line-length
    - '88'
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: 3.12.0
