repos:
- hooks:
  - args:
    - --config
    - 'pyproject.toml'
    id: black
  repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.0
- hooks:
  - additional_dependencies:
    - mypy
    args:
    - --config-file 
    - 'pyproject.toml'
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy/
  rev: v1.6.1
- hooks:
  - args:
    - --settings-path
    - 'pyproject.toml'
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.12.0
- hooks:
  - args:
    - --config
    - '.flake8'
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: 3.12.0
